/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mowers;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class App {

    public static void main(String[] args) {
        Simulation simulation = new Simulation();
        try {
            simulation.loadFromFile("test.txt");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        try {
            simulation.run();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        /*Mower m1 = new Mower("m1", new Coordinate(0, 1), Orientation.NORTH);
        m1.rightRotate();
        System.out.println(m1.getForwardCoordinate());
        System.out.println(m1);
        Set<Coordinate> set = new HashSet<Coordinate>();
        set.add(m1.getCoordinate());
        set.remove(m1.getCoordinate());
        System.out.println(m1.getCoordinate());
        System.out.println(set);*/

    }
}
